### Create Category
POST http://localhost:5000/category/add
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxZGVjYWU2NWEwOWY1NWFmYzk4NGJlZCIsImlhdCI6MTY0OTkxOTc5MCwiZXhwIjoxNjUwMTc4OTkwfQ.I-LS0R6TIOdMbc05go5dG4JcqRqjqQJ5WzCHGZvp-SY

{
    "name": "ASDASDASD",
    "user":{"_id":"61decae65a09f55afc984bed","name":"FRANNZ SUAVERDEZ","email":"frannz.suaverdez@tup.edu.ph","imageUrl":"https://lh3.googleusercontent.com/a-/AOh14GgREaiEW8OsPhR6xhl8os7L2WGYR8_OQfgiV-IJaQ=s96-c","googleId":"118121206790889149785","isAdmin":true,"categoryPermission":[],"subCategoryPermission":[],"createdAt":"2022-01-12T12:34:46.571Z","updatedAt":"2022-04-14T07:03:10.586Z","__v":0,"token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxZGVjYWU2NWEwOWY1NWFmYzk4NGJlZCIsImlhdCI6MTY0OTkxOTc5MCwiZXhwIjoxNjUwMTc4OTkwfQ.I-LS0R6TIOdMbc05go5dG4JcqRqjqQJ5WzCHGZvp-SY"}
}

### Get All Categories
GET http://localhost:5000/category/getAll



### Get All Categories
GET http://localhost:5000/user/auth/permissions/628891d01fe2d3e6b44fef82

###
POST http://localhost:5000/subcategory/add
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyODg5MWQwMWZlMmQzZTZiNDRmZWY4MiIsImlhdCI6MTY1MzgyNjgxNiwiZXhwIjoxNjU0MDg2MDE2fQ.fb0x1ygnBrEFwb_TLaoEcu-jw5w96s6kzoY_oGewTPQ

{
    "name": "ASDASDASD",
    "description": "ASDASDASD",
    "categoryId":"62639873448ef680c7b59a7f"
}

###
PUT http://localhost:5000/subcategory/edit/626e118bf2dff4103a9cdf25
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyODg5MWQwMWZlMmQzZTZiNDRmZWY4MiIsImlhdCI6MTY1MzgyNjgxNiwiZXhwIjoxNjU0MDg2MDE2fQ.fb0x1ygnBrEFwb_TLaoEcu-jw5w96s6kzoY_oGewTPQ

{
    "name": "ASDASDASD",
    "description": "ASDASDASD",
    "categoryId":"626e118bf2dff4103a9cdf25"
}

###
PUT http://localhost:5000/category/delete/62639873448ef680c7b59a7f
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyODg5MWQwMWZlMmQzZTZiNDRmZWY4MiIsImlhdCI6MTY1MzgyNjgxNiwiZXhwIjoxNjU0MDg2MDE2fQ.fb0x1ygnBrEFwb_TLaoEcu-jw5w96s6kzoY_oGewTPQ


###
POST http://localhost:5000/user/mobile/add/61decae65a09f55afc984bed
content-type: application/json

{
    "mobileNumber": "09273776823"
}



###
PUT http://localhost:5000/user/mobile/edit/61decae65a09f55afc984bed
content-type: application/json

{
    
    "mobileNumber": "09277718892"
}


###
DELETE http://localhost:5000/post/comment/delete
content-type: application/json

{
    "postId": "62a2f314d9412bbc039cf7c9",
    "commentId":"62a374c23163fca53d500c37"
}




###
GET http://localhost:5000/user/getAll
content-type: application/json

###
POST http://localhost:5000/filteredword/add
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxZGVjYWU2NWEwOWY1NWFmYzk4NGJlZCIsImlhdCI6MTY1NDA4MzYyMSwiZXhwIjoxNjU0MDkwODIxfQ.LFia-8zqw6zlNmo61d3noTE43-6uLtXEyH84rbDWUUg


{
    "word":"test1111"
}


###
GET http://localhost:5000/filteredword/getAll
content-type: application/json


###
GET http://localhost:5000/post/email
content-type: application/json

###
GET http://localhost:5000/post/sms
content-type: application/json



###
GET http://localhost:5000/post/getAll/home/1?searchQuery=entry
content-type: application/json

{
    "searchQuery":"",
    "category":"",
    "subcategory":"",
    "fromDate":""
}

####
GET http://localhost:5000/post/recommended/62a4196293e5c973c1e9ec82
content-type: application/json
